FROM biznetgio/horizon:dev-static

ENV HORIZON_BASEDIR=/opt/horizon \
    LANG=C \
    VERSION="stable/pike-gio"

COPY . ${HORIZON_BASEDIR}
WORKDIR ${HORIZON_BASEDIR}
RUN \
  apt-get update
RUN \
#    git clone -b stable/pike https://github.com/openstack/neutron-lbaas-dashboard.git && \
    cd neutron-lbaas-dashboard && \
    python -m pip install . && \
    python setup.py sdist && \
    python setup.py install && \
    cp neutron_lbaas_dashboard/enabled/_1481_project_ng_loadbalancersv2_panel.py ${HORIZON_BASEDIR}/openstack_dashboard/local/enabled
RUN cd ${HORIZON_BASEDIR} && \
    rm ${HORIZON_BASEDIR}/openstack_dashboard/wsgi/horizon.wsgi && \
    cp openstack_dashboard/local/local_settings.py.dev openstack_dashboard/local/local_settings.py && \
    ./manage.py compilemessages && \
    ./manage.py collectstatic --noinput && \
    ./manage.py compress --force && \
    ./manage.py make_web_conf --wsgi && \
    python -m compileall $HORIZON_BASEDIR

EXPOSE 8000
ENTRYPOINT ["/opt/horizon/manage.py","runserver","0.0.0.0:8000"]
